export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_SESSIONS_BEGIN = 'GET_SESSIONS_BEGIN';
export const GET_SESSIONS_SUCCESS = 'GET_SESSIONS_SUCCESS';
export const GET_SESSIONS_FAIL = 'GET_SESSIONS_FAIL';

export const GET_SPEAKERS_BEGIN = 'GET_SPEAKERS_BEGIN';
export const GET_SPEAKERS_SUCCESS = 'GET_SPEAKERS_SUCCESS';
export const GET_SPEAKERS_FAIL = 'GET_SPEAKERS_FAIL';

export const UPDATE_SESSION = 'UPDATE_SESSION';
export const HANDLE_FILTER_INPUT = 'HANDLE_FILTER_INPUT';
export const CLEAR_FILTER = 'CLEAR_FILTER';
